{
    'name': 'Dynamic Dashboard',
    'version': '18.0.1.0.0',
    'category': 'Tools',
    'summary': 'Configurable dashboard with cards, charts, drag & drop, ACL',
    'author': 'Figo Arbiansyah',
    'website': 'https://www.figo.my.id',
    'depends': ['base', 'web'],
    'data': [
        'security/dashboard_security.xml',
        'security/ir.model.access.csv',
        'views/dashboard_board_views.xml',
        'views/dashboard_component_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dynamic_dashboard_18/static/src/scss/dashboard.scss',
            'dynamic_dashboard_18/static/src/components/dashboard/dashboard.js',
            'dynamic_dashboard_18/static/src/components/dashboard/dashboard.xml',
            'dynamic_dashboard_18/static/src/components/card_metric/card_metric.js',
            'dynamic_dashboard_18/static/src/components/card_metric/card_metric.xml',
            'dynamic_dashboard_18/static/src/components/chart_widget/chart_widget.js',
            'dynamic_dashboard_18/static/src/components/chart_widget/chart_widget.xml',
            'dynamic_dashboard_18/static/src/components/config_dialog/config_dialog.js',
            'dynamic_dashboard_18/static/src/components/config_dialog/config_dialog.xml',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'images': [],
}
